FROM fedora:latest AS baseline
RUN dnf -yqq install httpd
EXPOSE 80
ENTRYPOINT /usr/sbin/httpd -DFOREGROUND

FROM baseline AS website1
ADD website1.html /var/www/html/website1.html
LABEL website=1

FROM baseline AS website2
ADD website2.html /var/www/html/website2.html
LABEL website=2